# Generated by Django 4.1.5 on 2023-02-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_alter_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
