# Generated by Django 4.1.5 on 2023-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmodel',
            name='number_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buildingmodel',
            name='stats_since',
            field=models.DateField(default='2023-03-20'),
        ),
    ]
