# Generated by Django 4.1.5 on 2023-03-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmodel',
            name='last_done',
            field=models.DateTimeField(default='2023-01-01 00:00:00'),
        ),
    ]
