# Generated by Django 4.1.5 on 2023-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_buildingmodel_last_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmodel',
            name='stats_since',
            field=models.DateField(default='2023-03-20'),
        ),
    ]
