# Generated by Django 4.1.5 on 2023-03-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_buildingmodel_last_done'),
        ('leaderboard', '0004_buildingmodel_number_submissions_and_more'),
    ]

    operations = [
    ]
