# Generated by Django 4.1.5 on 2023-03-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_merge_20230321_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmodel',
            name='stats_since',
            field=models.DateField(default='2023-03-21'),
        ),
    ]
