# Generated by Django 4.1.5 on 2023-03-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_alter_buildingmodel_stats_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmodel',
            name='last_done',
            field=models.DateTimeField(default='2023-01-01 00:00:00 +0000'),
        ),
    ]
