# Generated by Django 4.1.5 on 2023-03-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_alter_buildingmodel_stats_since'),
        ('leaderboard', '0007_alter_buildingmodel_last_done'),
    ]

    operations = [
    ]
