# Generated by Django 4.1.5 on 2023-03-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_alter_buildingmodel_co2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmodel',
            name='f_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
