# Generated by Django 4.1.5 on 2023-03-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_merge_20230321_1440'),
        ('leaderboard', '0009_alter_buildingmodel_co2_and_more'),
        ('leaderboard', '0009_alter_buildingmodel_stats_since'),
    ]

    operations = [
    ]
