# Generated by Django 4.1.5 on 2023-03-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0009_buildingmodel_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmodel',
            name='norm_co2',
            field=models.FloatField(default=0),
        ),
    ]
