# Generated by Django 4.1.5 on 2023-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_buildingmodel_norm_co2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingmodel',
            name='stats_since',
            field=models.DateField(default='2023-03-23'),
        ),
    ]
