# Generated by Django 4.1.5 on 2023-02-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_imagesubmission_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesubmission',
            old_name='Turner off Plug Sockets?',
            new_name='Turned off Plug Sockets?',
        ),
    ]
