# Generated by Django 4.1.5 on 2023-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
