# Generated by Django 4.1.5 on 2023-03-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_submission',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
