# Generated by Django 4.1.5 on 2023-03-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_last_submission_customuser_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_mod',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
    ]
