# Generated by Django 4.1.5 on 2023-03-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_is_mod_remove_customuser_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_daily_task',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
