# Generated by Django 4.1.5 on 2023-03-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_daily_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_daily_task',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_submission',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
