# Generated by Django 4.1.5 on 2023-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('ALEXANDER', 'Alexander'), ('AMORY', 'Amory'), ('BILLDOUGLASCINEMAMUSEUM', 'Bill Douglas Cinema Museum'), ('BUSINESSSCHOOLBUILDINGONE', 'Business School Building:One'), ('BYRNEHOUSE', 'Byrne House'), ('CATHOLICCHAPLAINCY', 'Catholic Chaplaincy'), ('CENTREFORRESILLIENCEINENVIRONMENT,WATERANDWASTE', 'Centre for Resillience in Environment, Water and Waste'), ('CLAYDEN', 'Clayden'), ('CLYDESDALEHOUSE', 'Clydesdale House'), ('CORNWALLHOUSE', 'Cornwall House'), ('CORNWALLHOUSESWIMMINGPOOL', 'Cornwall House Swimming Pool'), ('DEVONSHIREHOUSE', 'Devonshire House'), ('DIGITALHUMANITIESLAB', 'Digital Humanities Lab'), ('EXETERNORTHCOTTTHEATRE', 'Exeter Northcott Theatre'), ('ESTATESERVICECENTRE', 'Estate Service Centre'), ('FAMILYCENTREOWLETS', 'Family Centre (Owlets)'), ('FORUM', 'Forum'), ('GEOFFREYPOPE', 'Geoffrey Pope'), ('GREATHALLANDUNIVERSITYRECEPTION', 'Great Hall and University Reception'), ('HARRISON', 'Harrison'), ('MATHEMATICALSCIENCES', 'Mathematical Sciences'), ('HATHERLY', 'Hatherly'), ('HENRYWELLCOMEBUILDINGFORBIOCATALYSIS', 'Henry Wellcome Building for Biocatalysis'), ('HOPEHALL', 'Hope Hall'), ('INNOVATIONCENTREPHASE1AND2', 'Innovation Centre Phase 1 and 2'), ('INSTITUTEOFARABANDISLAMICSTUDIES', 'Institute of Arab and Islamic Studies'), ('INTOINTERNATIONALSTUDYCENTRE', 'INTO International Study Centre'), ('KAYBUILDING', 'Kay Building'), ('KAYHOUSEDURYARD', 'Kay House Duryard'), ('KNIGHTLEY', 'Knightley'), ('STRATEGYANDSECURITYINSTITUTE', 'Strategy and Security Institute'), ('LAFROWDAHOUSE', 'Lafrowda House'), ('LAVER', 'Laver'), ('LAZENBY', 'Lazenby'), ('LIBRARY', 'Library'), ('LIVINGSYSTEMS', 'Living Systems'), ('MAINRECEPTION', 'Main Reception'), ('MARYHARRISMEMORIALCHAPEL', 'Mary Harris Memorial Chapel'), ('NEWMAN', 'Newman'), ('NORTHCOTEHOUSE', 'Northcote House'), ('OLDLIBRARY', 'Old Library'), ('PETERCHALKCENTRE', 'Peter Chalk Centre'), ('PHYSICS', 'Physics'), ('QUEENS', "Queen's"), ('REDCOT', 'Redcot'), ('REEDHALL', 'Reed Hall'), ('REEDMEWSWELLBEINGCENTRE', 'Reed Mews Wellbeing Centre'), ('ROBOROUGH', 'Roborough'), ('RUSSELLSEALFITNESSCENTRE', 'Russell Seal Fitness Centre'), ('SIRCHRISTOPHERONDAATJEDEVONCRICKETCENTRE', 'Sir Christopher Ondaatje Devon Cricket Centre'), ('SIRHENRYWELLCOMEBUILDINGFORMOODDISORDERSRESEARCH', 'Sir Henry Wellcome Building for Mood Disorders Research'), ('SPORTSPARK', 'Sports Park'), ('STDAVIDSRETAILSERVICES', "St David's Retail Services"), ('STREATHAMCOURT', 'Streatham Court'), ('STREATHAMFARM', 'Streatham Farm'), ('STUDENTHEALTHCENTRE', 'Student Health Centre'), ('SOUTHWESTINSTITUTEOFTECHNOLOGY', 'South West Institute of Technology'), ('TENNISCENTRE', 'Tennis Centre'), ('THORNLEA', 'Thornlea'), ('UNIVERSITYRECEPTIONANDGREATHALL', 'University Reception and Great Hall'), ('VICAMBLERSHORTGAMETRAININGCENTREGOLF', 'Vic Ambler Short Game Training Centre (Golf)'), ('WASHINGTONSINGER', 'Washington Singer'), ('XFI', 'Xfi')], max_length=48)),
                ('name', models.CharField(max_length=100)),
                ('number_of_lights', models.IntegerField()),
                ('number_lights_on', models.IntegerField()),
                ('number_of_windows', models.IntegerField()),
                ('number_windows_open', models.IntegerField()),
                ('number_plugs', models.IntegerField()),
                ('number_plugs_on', models.IntegerField()),
                ('litter_items', models.IntegerField()),
                ('number_submissions', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='imagesubmission',
            name='room',
            field=models.CharField(max_length=100),
        ),
    ]
