# Generated by Django 4.1.5 on 2023-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_roommodel_alter_imagesubmission_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesubmission',
            name='lights',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='no_litter',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='sockets_off',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='windows',
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='litter_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='number_lights_on',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='number_of_lights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='number_of_windows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='number_plugs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='number_plugs_on',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='number_windows_open',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='litter_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='number_lights_on',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='number_of_lights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='number_of_windows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='number_plugs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='number_plugs_on',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='number_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='number_windows_open',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
