# Generated by Django 4.1.5 on 2023-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_imagesubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesubmission',
            name='date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
