# Generated by Django 4.1.5 on 2023-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_imagesubmission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesubmission',
            name='number_lights_on',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='number_of_lights',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='number_of_windows',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='number_plugs',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='number_plugs_on',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='number_windows_open',
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='lights_status',
            field=models.CharField(choices=[(
                'OFF', 'Off'), ('AUTO', 'Automatic'), ('ON', 'On')], default='OFF', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='windows_status',
            field=models.CharField(choices=[(
                'CLOSE', 'Closed'), ('AUTO', 'Automatic'), ('OPEN', 'Open')], default='CLOSE', max_length=5),
            preserve_default=False,
        ),
    ]
