# Generated by Django 4.1.5 on 2023-03-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_remove_imagesubmission_number_lights_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='number_of_lights',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='number_of_windows',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='number_plugs',
        ),
        migrations.RemoveField(
            model_name='roommodel',
            name='number_plugs_on',
        ),
    ]
