# Generated by Django 4.1.5 on 2023-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_remove_roommodel_number_of_lights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='last_done',
            field=models.DateTimeField(default='2023-01-01 00:00:00 +0000'),
            preserve_default=False,
        ),
    ]
