# Generated by Django 4.1.5 on 2023-03-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_remove_roommodel_number_of_lights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesubmission',
            name='submission_id',
            field=models.IntegerField(default=0),
        ),
    ]
