# Generated by Django 4.1.5 on 2023-03-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_imagesubmission_submission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesubmission',
            name='submission_id',
        ),
    ]
