# Generated by Django 4.1.5 on 2023-03-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_alter_roommodel_last_done'),
        ('submission', '0009_remove_imagesubmission_submission_id'),
    ]

    operations = [
    ]
