# Generated by Django 4.1.5 on 2023-03-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_alter_imagesubmission_building_and_more'),
        ('submission', '0010_merge_20230320_1646'),
    ]

    operations = [
    ]
