# Generated by Django 4.1.5 on 2023-03-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_merge_20230321_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='last_done',
        ),
    ]
