# Generated by Django 4.1.5 on 2023-03-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_alter_roommodel_last_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='last_done',
            field=models.DateTimeField(default='2023-01-01 00:00:00 +0000'),
        ),
    ]
