# Generated by Django 4.1.5 on 2023-03-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_merge_20230321_1144'),
        ('submission', '0015_alter_roommodel_last_done'),
    ]

    operations = [
    ]
