# Generated by Django 4.1.5 on 2023-02-27 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_user_email_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=uuid.uuid1, max_length=50),
        ),
    ]
