# Generated by Django 4.1.5 on 2023-03-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_user_email_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
